apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orderflow-dev
namePrefix: dev-
resources:
  - ../../base
patches:
  - path: replicas-patch.yaml
  - path: resources-patch.yaml
