{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orderflow-saga.serviceAccountName" . }}
  labels:
    {{- include "orderflow-saga.labels" . | nindent 4 }}
{{- end }}