image:
  repository: redpandadata/redpanda
  tag: "v24.2.7"
  pullPolicy: IfNotPresent

replicas: 1

storage:
  size: 4Gi
  accessModes:
    - ReadWriteOnce

service:
  ports:
    - name: kafka
      port: 9092
    - name: admin
      port: 9644

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

config:
  redpanda:
    rpc_server:
      address: 0.0.0.0:33145
    kafka_api:
      - address: 0.0.0.0:9092
        name: internal
    admin:
      - address: 0.0.0.0:9644
    developer_mode: true

