kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # service host:container port mappings — match the production docker-compose ports
      - { containerPort: 30080, hostPort: 8081, protocol: TCP }   # order
      - { containerPort: 30081, hostPort: 8082, protocol: TCP }   # payment
      - { containerPort: 30082, hostPort: 8083, protocol: TCP }   # inventory
      - { containerPort: 30083, hostPort: 8084, protocol: TCP }   # saga
      - { containerPort: 30090, hostPort: 9092, protocol: TCP }   # redpanda
      - { containerPort: 30091, hostPort: 9644, protocol: TCP }   # redpanda admin
      - { containerPort: 30200, hostPort: 3000, protocol: TCP }   # grafana
      - { containerPort: 30201, hostPort: 9091, protocol: TCP }   # prometheus
      - { containerPort: 30202, hostPort: 3200, protocol: TCP }   # tempo
      - { containerPort: 30203, hostPort: 4317, protocol: TCP }   # otel-collector
networking:
  disableDefaultCNI: false
