apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "orderflow-redpanda.fullname" . }}-data
  labels:
    {{- include "orderflow-redpanda.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
