apiVersion: v1
kind: Service
metadata:
  name: {{ include "orderflow-redpanda.fullname" . }}
  labels:
    {{- include "orderflow-redpanda.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "orderflow-redpanda.selectorLabels" . | nindent 4 }}
