apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orderflow-payment.fullname" . }}
  labels:
    {{- include "orderflow-payment.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
