apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: orderflow
  namespace: argocd
spec:
  description: orderflow platform
  sourceRepos:
    - https://github.com/t0pm1x/orderflow.git
  destinations:
    - namespace: 'orderflow-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: ""
      kind: Deployment
    - group: ""
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: policy
      kind: PodDisruptionBudget
    - group: networking.k8s.io
      kind: Ingress