apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "orderflow-postgres.fullname" . }}
  labels:
    {{- include "orderflow-postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "orderflow-postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orderflow-postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.existingSecret }}
                  name: {{ .Values.secret.existingSecret }}
                  {{- else }}
                  name: {{ include "orderflow-postgres.fullname" . }}
                  {{- end }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.existingSecret }}
                  name: {{ .Values.secret.existingSecret }}
                  {{- else }}
                  name: {{ include "orderflow-postgres.fullname" . }}
                  {{- end }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.existingSecret }}
                  name: {{ .Values.secret.existingSecret }}
                  {{- else }}
                  name: {{ include "orderflow-postgres.fullname" . }}
                  {{- end }}
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.auth.username }}"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.auth.username }}"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "orderflow-postgres.fullname" . }}-data
        - name: init-scripts
          configMap:
            name: {{ include "orderflow-postgres.fullname" . }}-init
