apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orderflow-redis.fullname" . }}
  labels:
    {{- include "orderflow-redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "orderflow-redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orderflow-redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["redis-server"]
          args: ["/etc/redis/redis.conf"]
          ports:
            - name: redis
              containerPort: 6379
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/redis
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "orderflow-redis.fullname" . }}-data
        - name: config
          configMap:
            name: {{ include "orderflow-redis.fullname" . }}-config
